name = input("enter your name")
age = int(input("enter your age"))
print("hello", name)
print("next year you will be ", age + 1, "year old")
name = input("enter your name")
age = int(input("enter your age"))
print("hello",name)
print("you are" ,age, "year old")
print("next year you will be", age + 1, "year old")
